on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
        - name: Check out code 
          uses: "action/checkout@v4"

        - name: Setup GO
          uses: "action/setup-go@v5"
          with:
            go-verion: '1.23'
        
        - name: run build 
          run: ./scripts/buildprod.sh

