on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    steps:
        - name: Check out code 
          uses: actions/checkout@v4

        - name: Setup GO
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'
            
        - name: Install goose
          run: go install github.com/pressly/goose/v3/cmd/goose@latest

        - name: run build 
          run: ./scripts/buildprod.sh

        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'

        - name: Push image to GCP Artifact Registry
          run: gcloud builds submit --tag asia-east1-docker.pkg.dev/bootdev-notely-440114/bootdev-notely-ar-repo/gohomewho/notely:latest .

        - name: Run DB migration
          run: ./scripts/migrateup.sh

        - name: Deploy to Cloud Run
          run: gcloud run deploy notely --image asia-east1-docker.pkg.dev/bootdev-notely-440114/bootdev-notely-ar-repo/gohomewho/notely:latest --region asia-east1 --allow-unauthenticated --project bootdev-notely-440114 --max-instances=4

